# Generated by Django 2.2.5 on 2021-04-30 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_belt', models.CharField(max_length=50)),
                ('name_color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('color1', models.ImageField(blank=True, null=True, upload_to='')),
                ('color2', models.ImageField(blank=True, null=True, upload_to='')),
                ('color3', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern1', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern2', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern3', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern4', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Item2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_belt', models.CharField(max_length=50)),
                ('name_color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('color1', models.ImageField(blank=True, null=True, upload_to='')),
                ('color2', models.ImageField(blank=True, null=True, upload_to='')),
                ('color3', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern1', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern2', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern3', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern4', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
