# Generated by Django 2.2.5 on 2021-04-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_belt', models.CharField(max_length=50)),
                ('name_color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('color1', models.ImageField(blank=True, null=True, upload_to='')),
                ('color2', models.ImageField(blank=True, null=True, upload_to='')),
                ('color3', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern1', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern2', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern3', models.ImageField(blank=True, null=True, upload_to='')),
                ('pattern4', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
