# Generated by Django 2.2.5 on 2021-05-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Item2'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Item3'),
        ),
    ]
