# Generated by Django 2.2.5 on 2021-05-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210504_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product2',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product3',
        ),
        migrations.CreateModel(
            name='OrderItem3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Order')),
                ('product3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Item3')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Order')),
                ('product2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Item2')),
            ],
        ),
    ]
