# Generated by Django 2.2.5 on 2021-05-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210505_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem3',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem3',
            name='product3',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Item2'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Item3'),
        ),
        migrations.DeleteModel(
            name='OrderItem2',
        ),
        migrations.DeleteModel(
            name='OrderItem3',
        ),
    ]
